batch_size: 10
train_epoch: 10000
save_interval_epoch: 1000
learning_rate: 2.e-4
max_grad_norm: 1.0

sample_rate: 8000
wave_len: 12000

betamin: 1.e-4
betamax: 0.05
betalen: 50

random_pad: False

fp16: False #use 16-bit floating point operations for training
